### ISSUE TITLE
Pod::Spec.new do |s|   s.name             = 'CBDatabase'   s.version          = '0.1.0'   s.summary          = 'A simple wrapper around CoreData'   s.description      = 'A simple wrapper around CoreData. Developed by Coinbase Wallet team.'    s.homepage         = 'https://github.com/CoinbaseWallet/Databases'   s.license          = { :type => "AGPL-3.0-only", :file => 'LICENSE' }   s.author           = { 'Coinbase' => 'developer@toshi.org' }   s.source           = { :git => 'https://github.com/CoinbaseWallet/Databases.git', :tag => s.version.to_s }   s.social_media_url = 'https://twitter.com/coinbase'    s.ios.deployment_target = '10.0'   s.swift_version = '4.2'   s.source_files = 'ios/Source/**/*.swift'    s.dependency 'RxCocoa', '>= 4.4.0', '< 5.0.0'   s.dependency 'RxSwift', '>= 4.4.0', '< 5.0.0'   s.dependency 'BigInt',  '>= 3.1.0', '< 4.0.0' end

### ISSUE THREAD

**Issue by Benny1Blanco** [CoinbaseWallet/CBDatabase#45]

**Comment by harrycheng8** [comment]
#38

**Comment by Only1adhd228** [comment]
9fbc6f43a061ee4a6492d7657c1fe6c0dbe3182b

**Comment by ttloves2** [comment]
Alikeness.today ???  Or Electra.us

**Comment by Collinjeffords** [comment]
D

**Comment by Benny1Blanco** [comment]
### **** ### 
Pod::Spec.new do |s|   s.name             = 'CBDatabase'   s.version          = '0.1.0'   s.summary          = 'A simple wrapper around CoreData'   s.description      = 'A simple wrapper around CoreData. Developed by Coinbase Wallet team.'    s.homepage         = 'https://github.com/CoinbaseWallet/Databases'   s.license          = { :type => "AGPL-3.0-only", :file => 'LICENSE' }   s.author           = { 'Coinbase' => 'developer@toshi.org' }   s.source           = { :git => 'https://github.com/CoinbaseWallet/Databases.git', :tag => s.version.to_s }   s.social_media_url = 'https://twitter.com/coinbase'    s.ios.deployment_target = '10.0'   s.swift_version = '4.2'   s.source_files = 'ios/Source/**/*.swift'    s.dependency 'RxCocoa', '>= 4.4.0', '< 5.0.0'   s.dependency 'RxSwift', '>= 4.4.0', '< 5.0.0'   s.dependency 'BigInt',  '>= 3.1.0', '< 4.0.0' end>,
>

**Comment by Benny1Blanco** [comment]
[uft 8 requested signature page.txt](https://github.com/CoinbaseWallet/CBDatabase/files/7271154/uft.8.requested.signature.page.txt)
